import { Metadata } from "next"

export const metadata: Metadata = {
  // title: 'Next.js', => String type of title

  // Object type of title
  title: {
    // absolute: 'Next.js',
    default: 'Colin Code',
    template: "%s | Code"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
