export const metadata = {
  title: 'Login Page',
  description: 'Generated by developer',
}

export default function LoginLayout({
    children,
}:
    {
        children: React.ReactNode;
    }) {
    return (
        <>
            {children}
            <h3>Please login using email and password.</h3>
        </>
    )
}